### PR TITLE
Re: https://github.com/ruffle-rs/ruffle/pull/9385

### PR DESCRIPTION
**Pull request by danielhjacobs**

### CODE REVIEW

**Comment by danielhjacobs** [comment]
Regex matches:
- `avm2_stub_getter!(activation, "flash.display.Bitmap", "pixelSnapping");`
- `avm2_stub_setter!(activation, "flash.display.Bitmap", "pixelSnapping");`
- `avm2_stub_method!(activation, "flash.display.BitmapData", "applyFilter");`
- `avm2_stub_constructor!(activation, "Namespace");`
- `stub_method("flash.events.MouseEvent", "updateAfterEvent");`
- `stub_getter("flash.net.LocalConnection", "domain");`
- `stub_setter("flash.net.URLRequest", "data");`

All with a single capturing group that captures the class name.

**Comment by huwdp** [comment]
I can't see Bitmap set as partial in the matrix. Regex does work so must be something else wrong.

I'll fix this on the weekend.

Thank you for the contribution!

**Comment by huwdp** [comment]
I've been unexpectingly traveling all weekend so only now started to look into the remaning issue.

image

Regex is matching too much. I might split by semicolon before doing the matching so this doesn't happen.

**Comment by danielhjacobs** [comment]
Weird, i though using non-greedy quantifier like I thought I did would have stopped that.

**Pull request merged**
